name: 02 - Workflow Events

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show the triggering event
        run: echo "This workflow was triggered by ${{ github.event_name }} event."