name: 02 - Workflow Events

on: 
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show the triggering event
        run: echo "This workflow was triggered by ${{ github.event_name }} event."