name: 03 - Workflow Runners
on: 
  workflow_dispatch:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
          - name: Show the triggering event
            run: echo "This workflow is running on ${{ runner.os }}."
    
    windows-echo:
        runs-on: windows-latest
        steps:
          - name: Show the triggering event
            run: echo "This workflow is running on ${{ runner.os }}."
    mac-echo:
        runs-on: macos-latest
        steps:
          - name: Show the triggering event
            run: echo "This workflow is running on ${{ runner.os }}."
