name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Priting Folders
        run: |
          echo "Current Directory: $(pwd)"
          echo "Node Modules Directory: $(ls -la node_modules)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          ls -la
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test