name: 10 - Using Functions
on: 
    workflow_dispatch:
    pull_request:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print PR title
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"

      - name: Print PR labels
        run: |
          cat << EOF
          ${{ github.event.pull_request.labels }}
          EOF

      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title,'fix') }}
        run: |
          echo "I am a bug fix"

      - name: Sleep for 20 seconds
        run: |
          sleep 20

      - name: Failing step
        run: |
            echo "This step will fail"
            exit 1

      - name: I will be skipped
        run: echo "I will print if the previous step succeeds"
    
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if the any previous step fails"

      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled" 

      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print when the workflow is cancelled" 
