name: 11 - Working with Inputs
on: 
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Skip deployment and only print build output'
        default: false
        type: boolean
      target:
        description: 'Which environment the workflow will target'
        required: true
        type: environment
      tag:
        description: 'Release from which to build and deploy'
        default: v3
        type: choice
        options:
          - v1
          - v2
          - v3

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build
          run: |
            echo "Building from tag: ${{ github.event.inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.target }}
        needs: build
        if: ${{ github.event.inputs.dry-run == 'false' }}
        steps:
        - name: Deploy
          run: |
            echo "Deploying to environment: ${{ github.event.inputs.target }}"
