name: 12 - working with outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Status of the build job"
        type: choice
        default: success
        options:
          - success
          - failure
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "$GITHUB_OUTPUT"
      - name: build
        id: build
        run: |
          echo "Building the code..."
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying the code..."
          echo "Build status was successful, proceeding with deployment."