name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
    # backwards-compatibility:
    #   runs-on: ${{ matrix.os }}
    #   strategy:
    #     fail-fast: false
    #     matrix:
    #       os: 
    #         - ubuntu-latest
    #         - windows-latest
    #       node-version: [18.x, 20.x, 21.x]
    #       include:
    #         - os: ubuntu-latest
    #           node-version: 21.x
    #         - os: ubuntu-latest
    #           node-version: 16.x
    #   steps:
    #     # - name: Checkout code
    #     #   uses: actions/checkout@v4
    #     - name: Setup Node
    #       uses: actions/setup-node@v4
    #       with:
    #         node-version: ${{ matrix.node-version }}
    #     - name: Perform some tests
    #       run: |
    #         echo "Running on ${{ matrix.os }} with Node.js version ${{ matrix.node-version }}"
    #     - name: Perform some tests
    #       run: echo "Uploading Test Results"
    include-example:
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
              color: [red, green]
              shape: [circle, square]
              size: [small, large]
              include:
                - color: red
                  shape: triangle
                  size: small
                  opacity: 50
                - opacity: 50
                - color: red
                  opacity: 75
                - shape: circle
                  opacity: 100
        steps:
            # - name: Checkout code
            #   uses: actions/checkout@v4
            - name: Dummy step
              run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
        